#!/bin/bash
# $1: L|R
# $2: hostaddr
# $3..$N: hostport
# cartpf L 127.0.0.1 8000

SCRIPT_SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" >/dev/null 2>&1 && pwd  )"
source $SCRIPT_SRC_DIR/cart-config.sh

if [ $# -lt 3 ]; then
    echo "Not enough arguments supplied. Example: cartpf L 127.0.0.1 8080"
    exit 2
fi
SSH_ARGS=('-f' '-N')
for port in "${@:3}"
do
	SSH_ARGS=("${SSH_ARGS[@]}" "-$1")
	SSH_ARGS=("${SSH_ARGS[@]}" "localhost:$port:$2:$port")
done
gcloud beta compute ssh "${GCLOUD_FLAGS[@]}" "${GCLOUD_USERNAME}@${GCLOUD_VMNAME}" -- "${SSH_ARGS[@]}"

