#!/bin/bash
SCRIPT_SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" >/dev/null 2>&1 && pwd  )"
source $SCRIPT_SRC_DIR/cart-config.sh
gcloud compute instances stop "${GCLOUD_FLAGS[@]}" "${GCLOUD_VMNAME}"

