#!/bin/bash

SCRIPT_SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" >/dev/null 2>&1 && pwd  )"
source $SCRIPT_SRC_DIR/cart-config.sh
echo "Killing PIDs:"
ps -e -f | grep -- '-f -N' | grep -- 'ssh' | grep -- "google_compute_engine" | awk '{print $2}'
ps -e -f | grep -- '-f -N' | grep -- 'ssh' | grep -- "google_compute_engine" | awk '{print $2}' | xargs kill



